### ISSUE TITLE
New feature kubernetes only checks vs ocp

### ISSUE THREAD

**Issue by nissessenap** [Oscarlind/OpenShift#1]
# Why

To get a bigger use case from the rest of the kubernetes community

# How

Currently https://github.com/Oscarlind/OpenShift/blob/main/tools/surface-scanner/scanner.py uses both OCP and kubernetes API.
It would be awsome to have a flag that say k8s only.

And then ignore ocp tests. The easiest way to solve this is to probably split up the code in general and have a simple check to see if OCP=false or something like that.

Think about the abstraction, in the future you might want to support API specific tasks from lets say AKS or rancher.
This kind of abstraction would also be good when testing CRD:s in the future, lets say if you want to see if ArgoCD is feeling okay or not.

**Comment by Oscarlind** [comment]
Feature implemented through a check to see if the OCP Api is available or not.
```    
    try:
        oc_version = dyn_client.resources.get(api_version='config.openshift.io/v1', kind='ClusterOperator')
    except Exception:
        is_ocp = False
```
Also split up and moved tool to: https://github.com/Oscarlind/OpenShift/tree/main/tools/python/cluster-scanner

Waiting with closing issue until I've verified the solution works in a few more scenarios. :)

**Comment by Oscarlind** [comment]
Tested and verified that is works on minikube. Added a try/catch to see if the metrics-server is installed when doing the node check for k8s.
